end_point: wss://rpc.polkadot.io
keystore:
  walletFilePath: config/sample.key.json
  password: "p4ssw0rd"
rewardsDestination:
  mainDestinationAddress: 1HigsTaXZrCEEWkbUPwD4Rx6XpV7E9fnsom6ZCx42RJnimr # Change this!!
  mainDestinationShare: 80%
  dustDestinationAddress: 1HigsTaXZrCEEWkbUPwD4Rx6XpV7E9fnsom6ZCx42RJnimr # Change this!!