end_point: wss://rpc.polkadot.io
keystore:
  walletFilePath: config/sample.key.json
  password: "p4ssw0rd"
rewardsDestination:
  mainDestinationAddress: XYZ
  mainDestinationShare: 80%
  dustDestinationAddress: YZX